# Generated by Django 4.0.6 on 2022-07-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghesarjomlebot', '0002_alter_telegramchat_id_alter_telegramstate_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('file_id', models.CharField(max_length=512, verbose_name='File Id')),
                ('user_id', models.CharField(max_length=512, verbose_name='User Id')),
            ],
        ),
    ]
