# Generated by Django 4.0.6 on 2022-07-13 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghesarjomlebot', '0003_userpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userpost',
            name='OP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userPosts', to='ghesarjomlebot.telegramuser'),
        ),
    ]
