# Generated by Django 4.0.6 on 2022-07-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghesarjomlebot', '0004_remove_userpost_user_id_userpost_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='file_type',
            field=models.CharField(max_length=512, null=True, verbose_name='File type'),
        ),
    ]
